### ISSUE TITLE
Invocation of MonoMod fails; MonoMod unable to find file or assembly Mono.Cecil.

### ISSUE THREAD

**Issue by Lojemiru** [Brokemia/Courier#1]
The following error happens as `AsmMonoMod.EntryPoint.Invoke(null, new object[] { new string[] { asmFrom, asmTo + ".tmp" } });` is called. This issue has been replicated on both my and Solteris' devices.

For further clarification: This is running on a Win10 box, tested in multiple locations (Program Files, Desktop, on a different drive) to ensure that it was not a simple permission error.

```c#
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Cecil, Version=0.11.1.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e' or one of its dependencies. The system cannot find the file specified.
   at MonoMod.Program.Main(String[] args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at MiniInstaller.Program.RunMonoMod(String asmFrom, String asmTo) in D:\Users\Lojical\Desktop\The Messenger Modding\Courier\MiniInstaller\Program.cs:line 175
   at MiniInstaller.Program.Main(String[] args) in D:\Users\Lojical\Desktop\The Messenger Modding\Courier\MiniInstaller\Program.cs:line 58 ```

**Comment by Solteris-Dev** [comment]
To clarify: This issue is happening on the [release ZIP](https://github.com/Brokemia/Courier/releases/download/v0.1-alpha/Courier-installer.zip)
With these methods (all run on Ubuntu currently): 
* Windows 10 run with KVM
* Mono Package 
* Steam Proton
* Wine

**Comment by Brokemia** [comment]
Solved by running MiniInstaller.exe with Mono. New installers are in the works with Mono bundled in
